name: Build and Deploy
on:
  - push
  - pull_request

env:
  PLUGIN_VERSION: ${{ github.ref_name }}
  ARTIFACT_NAME: DescCron-${{ github.ref_name }}.zip

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - run: ./gradlew clean build --no-daemon
        env:
          ORG_GRADLE_PROJECT_PLUGIN_VERSION: ${{ env.PLUGIN_VERSION }}
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: build/distributions/${{ env.ARTIFACT_NAME }}
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-artifact
          path: ./artifacts

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          artifacts: "./artifacts/${{ env.ARTIFACT_NAME }}"
          draft: true
