name: Build
on:
  - push
  - pull_request
env:
  PLUGIN_VERSION: ${{ github.ref_name }}
  ARTIFACT_NAME: DescCron-${{ github.ref_name }}.zip
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: 'gradle'
      - run: ./gradlew clean build --no-daemon
        env:
          ORG_GRADLE_PROJECT_PLUGIN_VERSION: ${{ env.PLUGIN_VERSION }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/distributions/${{ env.ARTIFACT_NAME }}
      - name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "ref_name": "${{ github.ref_name }}",
              "run_id": "${{ github.run_id }}",
              "artifact_name": "${{ env.ARTIFACT_NAME }}"
            }
