name: Build and Deploy
on:
  - push
  - pull_request

env:
  PLUGIN_VERSION: ${{ github.ref_name }}
  ARTIFACT_NAME: DescCron-${{ github.ref_name }}.zip

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: 'gradle'
      - run: ./gradlew clean build --no-daemon
        env:
          ORG_GRADLE_PROJECT_PLUGIN_VERSION: ${{ env.PLUGIN_VERSION }}

  deploy:
    name: Create Guthub Release 
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          artifacts: build/distributions/${{ env.ARTIFACT_NAME }}
          draft: true
