name: Deploy
on:
  repository_dispatch:
    types:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.client_payload.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          run_id: ${{ github.event.client_payload.run_id }}
          name: ${{ github.event.client_payload.artifact_name }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.client_payload.ref }}
          name: ${{ github.event.client_payload.ref_name }}
          artifacts: ./${{ github.event.client_payload.artifact_name }}
          draft: true
